"""Capability taxonomy and keyword-based area tagging."""
from pathlib import Path

# (slug, display name) — order = page order on the index.
AREAS = [
    ("core-rdd", "Core / RDD / Scheduler"),
    ("sql-catalyst", "SQL & Catalyst"),
    ("ansi-types", "ANSI & Data Types"),
    ("builtin-functions", "Built-in Functions"),
    ("datasources-dsv2", "Data Sources & DSv2"),
    ("connectors", "Connectors (Kafka/JDBC/Parquet/ORC/Avro)"),
    ("structured-streaming", "Structured Streaming"),
    ("dstreams", "DStreams (legacy streaming)"),
    ("pyspark", "PySpark & Python UDFs"),
    ("pandas-on-spark", "pandas API on Spark"),
    ("arrow", "Arrow"),
    ("spark-connect", "Spark Connect"),
    ("mllib", "MLlib / ML"),
    ("graphx", "GraphX"),
    ("sparkr", "SparkR"),
    ("deploy", "Deploy (Standalone/YARN/Mesos/K8s)"),
    ("shuffle-storage", "Shuffle / Storage / Memory"),
    ("web-ui", "Web UI / History / Metrics"),
    ("security", "Security"),
    ("geospatial", "Geospatial"),
    ("build-lang", "Build & Language support"),
    ("misc", "Misc / Other"),
]

# Ordered rules: FIRST match wins. Put specific/narrow areas before broad ones
# (e.g. pandas-on-spark and spark-connect before generic pyspark/sql).
_RULES = [
    ("geospatial", ["st_", "geospatial", "geometry", "geography", " srid", "wkb", "wkt", "geo and time", " geo "]),
    ("spark-connect", ["spark connect", "connect client", "connect server", "connect:", "spark.connect",
                        "connect api", "connect plugin", "connect ml", "connect server", "sparkconnect"]),
    ("pandas-on-spark", ["pandas api on spark", "pandas-on-spark", "koalas", "ps.dataframe", "pandas_udf",
                          "pandas udf", "grouped map", "cogroup", "applyinpandas", "mapinpandas",
                          "datatypeops", "internalfield", "categoricalaccessor", "categoricalindex",
                          "ps.series", "missing.dataframe", "missing.series", "pandas grouped"]),
    ("arrow", ["arrow-optimized", "pyarrow", " arrow ", "arrow-based", "arrow ipc", "arrow batch",
               "arrow stream", "to_arrow", "arrow python", "arrow conversion", "arrowexec"]),
    ("structured-streaming", ["structured streaming", "streaming query", "watermark", "continuous processing",
                               "statestore", "state store", "foreachbatch", "microbatch", "micro-batch",
                               "session window", "sessionization", "flatmapgroupswithstate", "mapgroupswithstate",
                               "groupstate", "streaming source", "streaming sink", "streaming aggregation",
                               "streaming join", "kafka source", "kafka sink", "streaming write", "streaming read",
                               "availablenow", "streaming checkpoint", "dropduplicateswithinwatermark",
                               "stream-stream", "streaming state", "asyncprogress", "streamingquerylistener",
                               "basestreamingsource", "basestreamingsink", "streamexecution",
                               "compactiblefilestreamlog", "streamingquery", "streaming dedupe",
                               "streaming quer", "filestreamsource", "maxrate", "recentprogress",
                               "hdfsmetadatalog", "inputinfo"]),
    ("dstreams", ["dstream", " receiver", "streaming context", "kinesis", " flume", "twitter stream",
                   "streamingcontext", "statebykey", "javastreamingcontext", "writeaheadlog",
                   "write ahead log", " wal ", "mapwithstate", "foreachrdd", "receivedblocktracker"]),
    ("sparkr", ["sparkr", " r api", "r udf", "r dataframe", "dapply", "gapply", "roxygen", " cran",
                "r package", "sparkr::", " in r ", "r function", "r partitionby"]),
    ("mllib", ["mllib", "ml.pipeline", "ml pipeline", " estimator", "transformer", "classifier", "classification",
                "regression", "clustering", "kmeans", "k-means", " gbt", "gradient boost", "random forest",
                "decision tree", "word2vec", " lda ", "tf-idf", "feature selector", "featureselector",
                "vectorassembler", "vectorindexer", "onehotencoder", "standardscaler", " als ",
                "recommendation", "isotonic", "naive bayes", "logistic regression", "linear regression",
                "crossvalidator", "param grid", "ml model", "ml.feature", "ml.classification", "ml.regression",
                "univariatefeatureselector", "bucketizer", "binarizer", " pca ", "chisquare", "spark.ml",
                "spark.mllib", "gaussian mixture", "bisecting", "power iteration",
                "vectorslicer", "densevector", "sparsevector", " lsh", "onevsrest", "rformula",
                "maxabsscaler", "multilabelmetrics", "multiclassmetrics", "rankingmetrics",
                "quantilediscretizer", "treeensemble", " w2v ", "findsynonyms", "breeze.vector",
                "featuretransform", "stringindexer", "prefixspan", "logisticaggregator",
                "aggregationdepth", "tree model", "indextostring", "chisqselector",
                "elementwiseproduct", "polynomialexpansion", "minhash", "countvectorizer",
                "imputer", " glm", "frequent pattern", "fpgrowth", "summarizer",
                "gaussianmixturemodel", "naivebayesmodel", " mnb", " cnb", " bnb", "libsvmdatasource",
                "hashingtf", "alsmodel", "blockmatrix", "periodicrddcheckpointer", "nodeidcache",
                " fm ", "robustscaler", "predictraw", "predictprobability", "randomforest",
                "stopwordsremover", "localldamodel", "distributedldamodel", "indexedrowmatrix",
                "minmaxscaler", "regressor", "paramvalidations", "ml algos", "spark.logit",
                "dt/rf/gbt", "params.validateparams", " ann ", "vectorudt", "matrixudt", "jpmml",
                "trainvalidationsplit", "mlwritable", " lor ", " lir ", "weightedleastsquare",
                "randomdatagenerator", "randomrdds", "weibullgenerator", "ldamodel",
                "associationrules", " sgd ", "log-linear", "normal equation", "least squares",
                "defaultparamsreadable", "regextokenizer", "hasseed", "groupeddata",
                "ml.evaluation", "ml.tuning", " blas", "rowmatrix", "params.getordefault",
                "params.clear", "logisticgradient", "libsvmfileformat", "naivebayes", "lbfg",
                "survival analysis", "ldasuite", "ldautils", "ml.pca", "intarrayparam",
                "association rule", "weightcol", "ml evaluator", "ml params", "ml.param"]),
    ("graphx", ["graphx", "pregel", "graphframe", "connected components", "pagerank", "triangle count",
                 "label propagation", "shortest path", "vertexrdd", "edgerdd", " graph ", " bagel"]),
    ("connectors", ["kafka", " jdbc", "parquet", " orc", " avro", " csv", "json datasource", "json data source",
                     "hive metastore", "hive table", "hive serde", "hive udf", " hive ", "thrift", "hadoop",
                     " s3", "s3a", " gcs", " abfs", "orc reader", "parquet reader", "file format",
                     "text datasource", "datasource for", "sink connector", "source connector", "orc writer",
                     "parquet writer", "columnar reader", "filestatus", "filesystem",
                     "outputwriterfactory", "outputwriter", "hivecontext", "hivesqlastbuilder",
                     "sparksqlastbuilder", "metastorerelation", "sparkhivewritercontainer",
                     "testhive", "hivecompatibilitysuite", "hivesharedstate", "listleaffiles",
                     "warehouse path", "spark-warehouse", "hivetests", "jsonrelation",
                     "structobjectinspector", "hivegenericudtf", "dockerjdbcintegration"]),
    ("datasources-dsv2", ["data source v2", "datasource v2", "dsv2", "datasourcev2", "v2 catalog", "v2session",
                           "v2sessioncatalog", "table catalog", "catalog api", "catalog plugin", "file source",
                           "partition stats", "partition filter", "insertinto", "saveastable", "createtable",
                           "table provider", "supportsread", "supportswrite", "row-level", "delete/update",
                           "merge into", "table capability", "staged table", "session catalog", "namespaces",
                           "show tables", "alter table", "drop table", "externalcatalog", "sessioncatalog",
                           "hiveclient", "hivesessionstate", "analyze table", "create function",
                           "add archive", "list archives", "drop database", "catalogv2", "multi-catalog",
                           "tablecapability", "logicalrelation", "resolvesessioncatalog",
                           " table", "catalog", "datasourcescanexec", "createdatasourcetableasselect",
                           "overwriteoptions", "describe database", "alter database", "bucketing",
                           "data source options", "fileformat.", "batchwritehelper",
                           "repairtablecommand", "filetable"]),
    ("ansi-types", ["ansi", "interval type", "timestamp_ntz", "timestamp ntz", " decimal", "char/varchar",
                     " varchar", " char type", "variant type", "variant data", " data type", "collation",
                     " udt ", "user-defined type", "user defined type", " date type", " timestamp type",
                     " null type", "calendar interval", "year-month interval", "day-time interval", "type coercion",
                     "timestampformatter", "dateformatter", "stringtodate", "stringtotimestamp",
                     "to_timestamp", "currentdate", "timestamptostring", "zoneid", " timezone",
                     "java.time.instant", "java.time.localdate", "datetype", "timestamptype",
                     "calendarintervaltype", "binarytype", "floattype", "decimaltype", "arraytype",
                     "maptype", "structtype", "datatypes.", "calendarinterval", "bigdecimal"]),
    ("builtin-functions", ["built-in function", "builtin function", "sql function", "add function",
                            "add expression", "aggregate function", "window function", "table function",
                            " regexp", "current_user", "current_date", "current_timestamp", "current_",
                            " try_", "to_number", "to_char", " date_", "datetime", " decode ", " encode ",
                            " concat", "array function", "map function", "higher-order function", "lambda function",
                            " expression ", "expression not", "expression for", "new function", "the function of",
                            "as a function", "function for", "function to", "function support", "scalar function",
                            "expressioninfo", "expressiondescription", " expressions", "count_if",
                            "string expressions", "random expressions", "null expressions", "regex expressions",
                            "input_file_block", "dense_rank", "createmap", "desc function",
                            " bround", "assert_true", " xpath", "stringtranslate", "trimleft"]),
    ("security", ["security", "authentication", "encryption", "kerberos", " acl", " ssl", " tls",
                   " token", "credential", "path traversal", "authorization", "delegation token",
                   " secure ", "vulnerabilit", "cve-", " auth ", "sslcontextfactory", "commons-crypto"]),
    ("web-ui", ["web ui", " ui ", "history server", " metrics", "rest api", "prometheus", "event log",
                 "spark ui", "job description", "executor tab", "sql tab", "jobs table", "stage page",
                 "web page", "ui page", " dashboard", "timeline view", " grafana", "metrics system",
                 "metricssystem", " servlet", "webui", "ui for", "taskmetrics", "jobprogresslistener",
                 "metricfilter", "graphitesink", "executors page", "executors tab", "stages page",
                 "alljobspage", "jobspage", "storage page", "environment page", "historyserver",
                 "sparkui.", "progress bar"]),
    ("shuffle-storage", ["shuffle", "memory management", "off-heap", "off heap", " spill", "block manager",
                          "blockmanager", "storage level", "external shuffle", "fallback storage",
                          "unified memory", "memory manager", " cache ", "caching", " persist", "unpersist",
                          "disk store", "memory store", " tungsten", "push-based shuffle", "shuffle service",
                          "shuffle merge", "rdd cache", "memory usage", "memory leak", "compressioncodec",
                          "compressible", "compression codec", "compression scheme", "eventlog.compression",
                          "bytestobytesmap", "inmemoryrelation", "map output", "taskmemorymanager",
                          "sizeestimator", "inmemorycolumnartablescan", "page size"]),
    ("deploy", ["yarn", " mesos", "kubernetes", " k8s", "standalone", "cluster manager", "deploy mode",
                 "resource manager", "executor pod", "driver pod", "driver service", "local-cluster",
                 "spark submit", "spark-submit", "dynamic allocation", "resource profile", "resource request",
                 "node manager", "application master", " container", "decommission", "worker node",
                 "executor allocation", "cluster mode", "client mode", "applicationstate",
                 "openstack", "sparksubmit", "spark-daemon", "spark daemons", "spark_worker_memory",
                 "applicationdescription", "spark_master_"]),
    ("build-lang", ["scala 2.1", "scala 2.13", "scala 3", "java 8", "java 11", "java 17", "java 21",
                     " maven", " sbt", "upgrade to scala", "python 3.", "-snapshot", "setting version",
                     "docker registry", "docker image", "github actions", "branch-", " ci ", " jenkins",
                     "build/mvn", "pom.xml", "publish apache spark", "release script",
                     "compile with", "cross-build", "scalastyle", " spotless", "trigger ci", " infra",
                     " upgrade", " upgraded", " downgrade", "bump ", " dependenc", "checkstyle",
                     " netty", " jackson", " jetty", "joda-time", " guava", " janino", " asm ",
                     "snappy-java", "zstd-jni", " ivy ", "commons-io", "httpclient", "pyrolite",
                     "scalatest", " breeze ", " tachyon", "jsr305", "twitter4j", "json4s", "dropwizard",
                     "beanutils", "commons-lang", "xerces", "mockito", "aws-java-sdk", " antlr",
                     "genjavadoc", "spark assembly", "change-scala-version",
                     "license header", "javadoc warning", "compilation warning", " lgtm", " linter",
                     "eslint", "appveyor", "shade plugin", "pom dependency", "enforcer rule",
                     "dockerfile", " zinc ", "surefire"]),
    ("pyspark", ["pyspark", "python udf", "python worker", "python api", " py4j", "python 3", " pip ",
                  "python side", "python type", "python function", "topandas", "python data source",
                  "python packaging", "pyspark.sql", "pyspark.ml", "python client", "python test",
                  "python error", "python doc", "batchevalpython", "evalpythonexec", "pythonrdd"]),
    ("sql-catalyst", [" sql", "catalyst", "dataframe", "dataset", "optimizer", "query plan", "adaptive query",
                       " join", "aggregate", "subquery", "pushdown", "predicate", "codegen", "whole-stage",
                       "logicalplan", "logical plan", "physical plan", "analyzer", "cost-based", " cbo",
                       "partition pruning", "dynamic partition", " hint", " cte", "explain", " parser",
                       "sql syntax", "query execution", "constant folding", "column pruning",
                       " cast ", "coalesce", " union", " window ", " pivot", "group by", "order by", " limit",
                       " distinct", "case when", "null handling", "nested column", "correlated",
                       "lateral view", "rollup", "grouping sets", " cube ",
                       "unsaferow", "queryplan", "sparkplan", "treenode", "analysisexception",
                       "printschema", "schema pruning", "schemapruning", "from_json", "to_json",
                       "from_csv", "to_csv", "schema_of_json", "failuresafeparser", "unresolvedtable",
                       "unresolvedalias", "boolean simplification",
                       "schema", "statistics", "aggregation", "aggregator", "aggregat",
                       "column conflict", "columnname", "column position", "columns support",
                       "partition column", "partitioning column", "infer partition",
                       "number of partitions", "repartition", "return type is", "data type", "datatype",
                       " column", " partition", "type",
                       "columnarbatch", "hashedrelation", "hashjoin", "querystage",
                       "queryexecution", "cachemanager", "scalareflection", "lambdavariable",
                       "utf8string", "nestedcolumnaliasing", "analyzecolumncommand", "commandutils",
                       "datasourceoptions", "caseinsensitivestringmap", "sparkplan", "logicaltransform",
                       "generatedcolumn", "unsafekeyvaluesorter", "reflectivecalls", "postfixops",
                       "timsort", "planinteg", "expressionencoder", "scalaudf", "staticinvoke",
                       "resolvereferences", "likesimplification", "unsafekvexternalsorter",
                       "variablelengthrowbasedkeyvaluebatch", "generateprojection", "mutableprojection",
                       "cartesianproduct", "quantilesummaries", "offsetwindowframe", "windowexec",
                       "unsafearraydata", "unsafesorterspillreader", "rowbasedkeyvaluebatch",
                       "appendonlymap", "radix sort", "subquer", "temp view", "eageranalysis",
                       "canonicalize", "mapobjects", "sortmergejoin", "leftsemi", "leftanti",
                       "promoteprecision", "generateunsafeprojection", "logicallocaltable",
                       "reserved keyword", "create view", "drop view", "drop function",
                       "list file", "list jar", "sortorder", "simplifyconditionals",
                       "tocommentsafestring", "gencode", "dogencode", "exprcode",
                       "resolverelations", "statsreportlistener", "arraybasedmapdata",
                       "expand star", "extractvalue", "casekeywhen", "internalrow", "emptyrow",
                       " exchange", "overridefunctionregistry", "equalnullsafe", "platformdependent",
                       "crosstab", "grouping analytics", "resolveexpression",
                       "framelessoffsetwindowfunction", "showstring", "resolve alias"]),
    ("core-rdd", [" rdd", "scheduler", " task ", " dag", "accumulator", "broadcast", "serializer",
                   "serializ", "closure", "partitioner", "executor", " driver", "taskset", " stage ",
                   " job ", "listenerbus", "sparkcontext", "sparkconf", "sparksession", "spark core",
                   "fault tolerance", "speculation", "barrier execution", " checkpoint",
                   "contextcleaner", "taskcontext", " kryo", "pipedrdd", "piperdd",
                   "uninterruptiblethread", "statcounter", "stage.attemptid"]),
]

def load_overrides(path) -> dict[str, str]:
    result: dict[str, str] = {}
    p = Path(path)
    if not p.exists():
        return result
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        sid, _, area = line.partition("\t")
        if sid and area:
            result[sid.strip()] = area.strip()
    return result

def assign_area(spark_id, title, overrides) -> str:
    if spark_id and spark_id in overrides:
        return overrides[spark_id]
    hay = f" {title.lower()} "
    for slug, keywords in _RULES:
        if any(kw in hay for kw in keywords):
            return slug
    return "misc"
